### ISSUE TITLE
|BitGreen|bitg|bitg.org|

### ISSUE THREAD

**Issue by Erernaen** [project-ecc/ecchat#7]
bitgreen.conf set with
rpcport=9333
listen=0
upnp=0

**Comment by Erernaen** [comment]
Another one: |Qtum|qtum|qtum.org|
rpcport=3889
![qtum](https://user-images.githubusercontent.com/46646401/119953725-9629ec80-bf9e-11eb-8175-5dac8cbabc92.PNG)

**Comment by HenryYoung42** [comment]
Added - thanks !
